### ISSUE TITLE
EPIC: System.Text.Json

### ISSUE THREAD

**Issue by SebastianStehle** [Squidex/squidex#652]
Support System.Text.Json (STS) for faster performance and to make it easier to use state of the art libs like GraphQL.

* [x] Get rid of custom serializers when possible and replace with TypeConverter
* [x] Get rid of custom serializers and write surrogate serializer
* [x] Check casing in MongoDB deserialization.
* [x] Find a solution for Json schemas and inheritance in OpenAPI.
* [x] Write inheritance converter for STS
* [x] Write serializer for GeoJSON.
* [x] Get rid of ContentFieldDataConverter (JSON)?
* [x] Get rid of InstantSerializer (Mongo)?
* [x] CompareOperatorJsonConverter?
